#  Sonatype Nexus (TM) Open Source Version
#  Copyright (c) 2020-present Sonatype, Inc.
#  All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
#
#  Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
#  of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
#  Eclipse Foundation. All other trademarks are the property of their respective owners.
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0
  circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@dev:alpha

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

commands:
  remove-nancy:
    steps:
      - run:
          command: |
            if [ -f "/tmp/tools/nancy" ]; then
              rm /tmp/tools/nancy
              echo "Removed nancy"
            fi

jobs:
  job-test-install-default-nancy:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy
      - run:
          name: Check install old nancy version
          command: |
            installedNancyVersion=$(/tmp/tools/nancy --version | head -n 1)
            echo "installedNancyVersion: $installedNancyVersion"
            if [ "$installedNancyVersion" != "v0.0.41" ]; then
              >&2 echo "Wrong old nancy version output: $installedNancyVersion"
              exit 1
            fi

  job-test-install-old-nancy:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - remove-nancy
      - circleci-nancy-orb/install-nancy:
          nancy-version: v0.0.17
      - run:
          name: Check install old nancy version
          command: |
            installedNancyVersion=$(/tmp/tools/nancy --version | head -n 1)
            echo "installedNancyVersion: $installedNancyVersion"
            if [ "$installedNancyVersion" != "v0.0.17" ]; then
              >&2 echo "Wrong old nancy version output: $installedNancyVersion"
              exit 1
            fi

  job-test-install-platform-windows:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy:
          nancy-platform: windows.amd64
      - remove-nancy

  job-test-install-platform-macos:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy:
          nancy-platform: darwin.amd64
      - remove-nancy

  job-test-run-modfile:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - checkout
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy-modfile:
          modfile: test/non-vulnerable/go.sum

  job-test-run-default:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy

  job-test-run-options:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy:
          options: -quiet

  job-test-run-modfile-options:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy-modfile:
          options: -version

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      # this `lint-pack_validate_publish-dev` workflow will run on any commit
      - orb-tools/lint

      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: sonatype-nexus-community/circleci-nancy-orb
          requires:
            - orb-tools/pack

      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev

  # This `integration-tests` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-tests:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # integration tests
      # NOTE: When the Orb parameters change drastically, you may need to temporarily comment out this IT section to
      # allow the build to republish the new dev Orb. After a CI run completes with this IT section, you can restore
      # this IT section. Another approach may be to manually republish the dev Orb from you local machine when needed.
      - job-test-install-default-nancy
      - job-test-install-old-nancy
      - job-test-install-platform-windows
      - job-test-install-platform-macos
      - job-test-run-modfile
      - job-test-run-default
      - job-test-run-options
      - job-test-run-modfile-options

  # This workflow exists only to simplify running local IT builds, therefore it need never run on the CI server.
  wf_integration-test:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              ignore: /.*/
    jobs:
      # change the line below to run the IT job of you choice
      - job-test-run-default

  promote-patch:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: sonatype-nexus-community/circleci-nancy-orb
          requires:
            - orb-tools/pack
      - orb-tools/publish:
          #orb-path: orb.yml
          attach-workspace: true
          orb-ref: sonatype-nexus-community/circleci-nancy-orb@dev:${CIRCLE_BRANCH}
          requires:
            - orb-tools/publish-dev

      - approve-release:
          type: approval
          requires:
            - orb-tools/publish

#      - orb-tools/dev-promote-prod:
#          name: dev-promote-patch
#          orb-name: sonatype-nexus-community/circleci-nancy-orb
#          ssh-fingerprints: "d9:52:33:98:cd:80:5c:18:42:5e:fa:62:91:aa:55:2c"
#          requires:
#            - approve-release
