#  Sonatype Nexus (TM) Open Source Version
#  Copyright (c) 2020-present Sonatype, Inc.
#  All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
#
#  Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
#  of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
#  Eclipse Foundation. All other trademarks are the property of their respective owners.
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4

  my-inline-orb:
    version: 2.1
    description: |
      Use Nancy to check for vulnerabilities in your Golang dependencies.
      Full orb source code: https://github.com/sonatype-nexus-community/circleci-nancy-orb

    examples:
      run-nancy-golist-example:
        description: The configuration below will run nancy on your golang project dependencies.
          The default go list command will be used to pipe dependency information to nancy.
          It assumes a default architecture of linux.amd, nancy version v0.0.41.
        usage:
          version: 2.1

          orbs:
            circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

          jobs:
            job-nancy:
              executor: circleci-nancy-orb/golang-executor
              steps:
                - circleci-nancy-orb/install-nancy
                - circleci-nancy-orb/run-nancy

          workflows:
            main:
              jobs:
                - job-nancy

      run-nancy-gosum-example:
        description: The configuration below will run nancy on your golang project dependencies. It assumes a default
          architecture of linux.amd, nancy version v0.0.41, and a 'go.sum' file in the root of your project.
        usage:
          version: 2.1

          orbs:
            circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

          jobs:
            job-nancy:
              executor: circleci-nancy-orb/golang-executor
              steps:
                - circleci-nancy-orb/install-nancy
                - circleci-nancy-orb/run-nancy-modfile

          workflows:
            main:
              jobs:
                - job-nancy

      run-nancy-specific-version-platform-modfile-example:
        description: The configuration below will run nancy on your golang project dependencies. It specifies custom
          architecture (windows), nancy version (v0.0.40), and 'my-go.sum' file module file. It runs nancy with the
          -quiet option.
        usage:
          version: 2.1

          orbs:
            circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

          jobs:
            job-nancy:
              executor: circleci-nancy-orb/golang-executor
              steps:
                - circleci-nancy-orb/install-nancy:
                    nancy-platform: windows.amd64
                    nancy-version: v0.0.40
                - circleci-nancy-orb/run-nancy-modfile:
                    modfile: my-go.sum
                    option: -quiet

          workflows:
            main:
              jobs:
                - job-nancy


    executors:
      golang-executor:
        description: "CircleCI provided docker image with Golang installed. see: https://hub.docker.com/r/circleci/golang/"
        docker:
          - image: circleci/golang:1.12
            environment:
              - GO111MODULE=on

    commands:
      install-nancy:
        parameters:
          nancy-version:
            type: string
            default: v0.0.41
            description: >
              The version of Nancy to run. See: https://github.com/sonatype-nexus-community/nancy/releases for available
              versions.
          nancy-platform:
            type: string
            default: linux.amd64
            description: >
              The underlying OS on which Nancy will run. Valid values are: linux.amd64, darwin.amd64, windows.amd64.
              See: https://github.com/sonatype-nexus-community/nancy/releases for all available platforms.
              Please let us know if you find a need for another platform, or even better, submit a PR!
        steps:
          - run:
              name: Install Nancy
              command: |
                cd /tmp && mkdir tools && cd -
                sourceUrl="https://github.com/sonatype-nexus-community/nancy/releases/download/<< parameters.nancy-version >>/nancy-<< parameters.nancy-platform >>-<< parameters.nancy-version >>"
                if [[ $sourceUrl == *"windows"* ]]; then
                  sourceUrl="${sourceUrl}.exe"
                fi
                curl --fail -s -L "$sourceUrl" -o "/tmp/tools/nancy"
                chmod +x /tmp/tools/nancy

      run-nancy:
        parameters:
          golistcommand:
            type: string
            default: go list -m all
            description: >
              The go list command who's output will be piped to Nancy to read your project dependencies.
          options:
            type: string
            default: ""
            description: >
              Additional options to pass to nancy. Like: -quiet -exclude-vulnerability value
              See https://github.com/sonatype-nexus-community/nancy#usage for all valid options.
        steps:
          - run:
              name: Run Nancy
              command: |
                << parameters.golistcommand >> | /tmp/tools/nancy << parameters.options >>

      run-nancy-modfile:
        parameters:
          modfile:
            type: string
            default: go.sum
            description: >
              The path to the file from which Nancy will read your project dependencies.
              Typically the path to a file named `go.sum` or `Gopkg.lock`.
          options:
            type: string
            default: ""
            description: >
              Additional options to pass to nancy. Like: -quiet -exclude-vulnerability value
              See https://github.com/sonatype-nexus-community/nancy#usage for all valid options.
        steps:
          - run:
              name: Run Nancy modfile
              command: |
                /tmp/tools/nancy << parameters.options >> << parameters.modfile >>

jobs:
  job-extract-inline-orb:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - orb-tools/extract-inline-orb:
          orb: my-inline-orb
          source: inline-orb/config-inline.yml

  job-test-inline-orb:
    executor: my-inline-orb/golang-executor
    steps:
      - checkout
      - my-inline-orb/install-nancy
      - my-inline-orb/run-nancy
      - my-inline-orb/run-nancy-modfile:
          options: -quiet
          modfile: test/non-vulnerable/go.sum

workflows:
  # NOTE: Workflows below are not used for local inline development, and exist only as required for local config processing.
  main:
    jobs:
      - job-test-inline-orb
      - job-extract-inline-orb
