version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4

  my-inline-orb:
    version: 2.1
    description: |
      Use nancy (https://github.com/sonatype-nexus-community/nancy) to check for vulnerabilities in your Golang dependencies.

    examples:
      run-nancy-example:
        description: The configuration below will run nancy on your golang project dependencies. It assumes a default
          architecture of linux.amd, nancy version v0.0.41, and a 'go.sum' file in the root of your project.
        usage:
          version: 2.1

          orbs:
            circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

          workflows:
            main:
              jobs:
                - circleci-nancy-orb/run-nancy

      run-nancy-specific-version-platform-modfile-example:
        description: The configuration below will run nancy on your golang project dependencies. It specifies custom
          architecture (windows), nancy version (v0.0.40), and 'my-go.sum' file module file.
        usage:
          version: 2.1

          orbs:
            circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

          workflows:
            main:
              jobs:
                - circleci-nancy-orb/run-nancy:
                    nancy-platform: windows.amd64
                    nancy-version: v0.0.40
                    modfile: my-go.sum


    executors:
      golang-executor:
        description: "CircleCI provided docker image with Golang installed. see: https://hub.docker.com/r/circleci/golang/"
        docker:
          - image: circleci/golang:1.12

    nancy-defaults: &JOB_NANCY_DEFAULTS
      parameters:
        executor:
          type: executor
          default: golang-executor
      executor: <<parameters.executor>>

    commands:
      install-nancy:
        parameters:
          nancy-version:
            type: string
            default: v0.0.41
            description: >
              The version of Nancy to run. See: https://github.com/sonatype-nexus-community/nancy/releases for available
              versions.
          nancy-platform:
            type: string
            default: linux.amd64
            description: >
              The underlying OS on which Nancy will run. Valid values are: linux.amd64, darwin.amd64, windows.amd64.
              See: https://github.com/sonatype-nexus-community/nancy/releases for all available platforms.
              Please let us know if you find a need for another platform, or even better, submit a PR!
        steps:
          - run:
              name: Install Nancy
              command: |
                cd /tmp && mkdir tools && cd -
                curl -s -L "https://github.com/sonatype-nexus-community/nancy/releases/download/<< parameters.nancy-version >>/nancy-<< parameters.nancy-platform >>-<< parameters.nancy-version >>" -o "/tmp/tools/nancy"
                chmod +x /tmp/tools/nancy

      run-nancy:
        parameters:
          modfile:
            type: string
            default: go.sum
            description: >
              The path to the file from which Nancy will read you dependencies.
              Typically the path to a file named `go.sum` or `Gopkg.lock`.
        steps:
          - run:
              name: Run Nancy
              command: |
                /tmp/tools/nancy << parameters.modfile >>

    jobs:
      job-run-nancy:
        <<: *JOB_NANCY_DEFAULTS
        steps:
          - install-nancy
          - run-nancy


jobs:
  job-extract-inline-orb:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - orb-tools/extract-inline-orb:
          orb: my-inline-orb
          source: inline-orb/config-inline.yml

  job-test-inline-orb:
    executor: my-inline-orb/golang-executor
    steps:
      - checkout
      - my-inline-orb/install-nancy
      - my-inline-orb/run-nancy:
          modfile: test/non-vulnerable/go.sum

workflows:
  # NOTE: Workflows below are not used for local inline development, and exist only as required for local config processing.
  main:
    jobs:
      - job-test-inline-orb
      - job-extract-inline-orb
