golang-executor:
  description: "CircleCI provided docker image with Golang installed. see: https://hub.docker.com/r/circleci/golang/"
  docker:
    - image: circleci/golang:1.12
      environment:
        - GO111MODULE=on
