description: Specifies custom architecture (windows-amd64), nancy version (v1.0.6), and 'my-Gopkg.lock' file module file.
  It also runs nancy with the --quiet option.
usage:
  version: 2.1

  orbs:
    nancy: sonatype-nexus-community/circleci-nancy-orb@x.y.z

  jobs:
    job-nancy:
      executor: nancy/golang-executor
      steps:
        - checkout
        - nancy/install:
            nancy-platform: windows-amd64
            nancy-version: v1.0.6
        - nancy/run-modfile:
            modfile: my-Gopkg.lock
            options: sleuth --quiet -p

  workflows:
    main:
      jobs:
        - job-nancy
