description: Specifies custom architecture (windows-amd64), nancy version (v1.0.6), and 'my-Gopkg.lock' file module file.
  It runs nancy with the --quiet option and uses an executor with a golang container with tag 1.14
usage:
  version: 2.1

  orbs:
    nancy: sonatype-nexus-community/circleci-nancy-orb@x.y.z

  jobs:
    job-nancy:
      executor:
        name: nancy/golang-executor
        tag: 1.14
      steps:
        - checkout
        - nancy/install-nancy:
            nancy-platform: windows-amd64
            nancy-version: v1.0.6
        - nancy/run-modfile:
            modfile: my-Gopkg.lock
            options: sleuth --quiet -p

  workflows:
    main:
      jobs:
        - job-nancy
