version: 2.1
description: |
  Use nancy (https://github.com/sonatype-nexus-community/nancy) to check for vulnerabilities in your Golang dependencies.

examples:
  run-nancy-example:
    description: The configuration below will run nancy on your golang project dependencies.
    usage:
      version: 2.1

      orbs:
        circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@x.y.z

      workflows:
        main:
          jobs:
            - circleci-nancy-orb/run-nancy

executors:
  golang-executor:
    description: "CircleCI provided docker image with Golang installed. see: https://hub.docker.com/r/circleci/golang/"
    docker:
      - image: circleci/golang:1.12

nancy-defaults: &JOB_NANCY_DEFAULTS
  parameters:
    executor:
      type: executor
      default: golang-executor
    nancy-version:
      type: string
      default: v0.0.17
    nancy-platform:
      type: string
      default: linux.amd64
  executor: <<parameters.executor>>

commands:
  install-nancy:
    parameters:
      nancy-version:
        type: string
      nancy-platform:
        type: string
    steps:
      - run:
          name: Install Nancy
          command: |
            cd /tmp && mkdir tools && cd -
            curl -s -L "https://github.com/sonatype-nexus-community/nancy/releases/download/<< parameters.nancy-version >>/nancy-linux.amd64-<< parameters.nancy-version >>" -o "/tmp/tools/nancy"
            chmod +x /tmp/tools/nancy
            /tmp/tools/nancy --help
            ls -alh /tmp/tools/

  run-nancy:
    steps:
      - run:
          name: Run Nancy
          command: |
            ls -alh /tmp/tools/
            /tmp/tools/Nancy --help

jobs:
  job-install-nancy:
    <<: *JOB_NANCY_DEFAULTS
    steps:
      - install-nancy:
          nancy-version: << parameters.nancy-version >>
          nancy-platform: << parameters.nancy-platform >>
      - run-nancy
